const fs = require('fs');
const filePath = 'D:\\Projects\\Book Summary\\gist\\src\\data\\books\\intelligent-investor.chapters.json';
const j = JSON.parse(fs.readFileSync(filePath, 'utf8'));

const additions = {
  '1. Investment versus Speculation': '\n\nGraham emphasizes that the distinction between investment and speculation is fundamental to every financial decision, and that failing to maintain this clarity has been the root cause of countless financial disasters throughout history. The intelligent investor must develop the self-awareness to recognize when they are crossing the line from analysis-based decisions to hope-based gambles, and must have the discipline to step back when emotions threaten to overwhelm rational judgment.',
  '2. The Investor and Inflation': '\n\nGraham concludes that investors should focus on building wealth through disciplined saving and investing rather than trying to hedge specific macroeconomic risks. The most reliable protection against inflation is a diversified portfolio of productive assets purchased at reasonable prices, combined with a savings habit that increases exposure to real assets over time. Chasing inflation hedges after they have already appreciated typically destroys rather than creates value.',
  '3. A Century of Stock-Market History': '\n\nThe historical record also demonstrates that market extremes eventually reverse, creating opportunities for investors who maintain their discipline during difficult periods. Graham notes that the worst market environments often precede the best returns, reinforcing the importance of staying invested through all conditions rather than attempting to time entries and exits based on predictions about future market direction.',
  '4. General Portfolio Policy: The Defensive Investor': '\n\nThe defensive investor should also consider their overall financial situation, including employment stability, family obligations, and other sources of income when determining the appropriate stock-bond allocation. Graham emphasizes that the right allocation is personal and depends on individual circumstances rather than on market conditions or popular opinion, and that the chosen allocation should be maintained consistently through all market environments.',
  '5. The Defensive Investor and Common Stocks': '\n\nGraham also recommends that defensive investors consider the tax implications of their investment strategies, noting that tax-efficient approaches can significantly enhance after-tax returns over time. The combination of moderate growth, dividend income, and conservative valuation creates a portfolio that can compound wealth effectively while minimizing the risk of permanent capital loss, making it suitable for investors who prioritize safety and steady returns.',
  '6. Portfolio Policy for the Enterprising Investor: Negative Approach': '\n\nThe negative approach also serves as a framework for evaluating new investment opportunities, as the enterprising investor should first consider what could go wrong before focusing on potential returns. Graham emphasizes that avoiding losses is more important than achieving gains, as recovered losses earn nothing while avoided losses can be redirected to productive investments that compound over time.',
  '7. Portfolio Policy for the Enterprising Investor: The Positive Side': '\n\nGraham emphasizes that the enterprising investor must develop the emotional discipline to hold unpopular positions for extended periods, as market recognition of value can take much longer than expected. The combination of analytical skill and psychological resilience is essential for success in active investing strategies that seek to exploit market inefficiencies and temporary mispricings.',
  '8. The Investor and Market Fluctuations': '\n\nGraham also notes that market fluctuations create opportunities for investors who can maintain a long-term perspective, as short-term price movements often create significant disparities between price and value. The intelligent investor benefits from volatility rather than being harmed by it, provided they have the discipline to exploit opportunities rather than being swept up in market emotion and following the crowd.',
  '9. Investing in Investment Funds': '\n\nThe key to successful fund investing is selecting low-cost, consistently performing funds with conservative objectives and maintaining a long-term perspective. Graham emphasizes that investors should evaluate fund performance over multiple market cycles rather than focusing on recent results, as short-term performance is often driven by factors that may not persist and rarely predicts future returns reliably.',
  '10. The Investor and His Advisers': '\n\nGraham emphasizes that the intelligent investor should develop their own analytical capabilities rather than relying entirely on others, as independent thinking is essential for long-term investment success. The most valuable use of professional advice is to supplement rather than replace personal judgment, providing information and perspectives that enhance the investor own analysis and decision-making process.',
  '11. Security Analysis for the Lay Investor: General Long-Term Prospects': '\n\nGraham emphasizes that the analyst should always consider the downside scenario as carefully as the upside scenario, as the margin of safety is designed to protect against adverse outcomes rather than to maximize expected returns. Conservative analysis provides the foundation for sound investment decisions, even when it means missing some opportunities that appear attractive on the surface but lack adequate protection against downside risk.',
  '12. Things to Consider About Per-Share Earnings': '\n\nGraham recommends that investors develop their own internal standards for evaluating earnings quality, focusing on cash generation, consistency, and the alignment of reported figures with underlying economic reality. The ability to assess earnings quality independently is one of the most valuable skills an investor can develop, as it provides protection against the many traps embedded in reported financial figures that can mislead even sophisticated observers.',
  '13. A Comparison of Four Listed Companies': '\n\nGraham emphasizes that this comparison illustrates a broader principle: the market often confuses popularity with value, creating opportunities for investors who can distinguish between the two. The discipline to buy statistically cheap companies while avoiding popular favorites is essential for long-term investment success, even when it requires going against prevailing market sentiment and enduring periods of underperformance.',
  '14. Stock Selection for the Defensive Investor': '\n\nGraham emphasizes that the defensive investor should not spend excessive time on stock selection, as the primary objective is to build a solid portfolio with minimal effort and risk. The screening criteria are designed to be applied quickly and systematically, allowing the investor to focus on maintaining discipline rather than making frequent changes based on short-term market movements or news events.',
  '15. Stock Selection for the Enterprising Investor': '\n\nGraham emphasizes that the enterprising investor must be prepared to act independently and think differently from the crowd, as the most profitable opportunities often arise when consensus opinion is most pessimistic. The combination of thorough analysis, emotional discipline, and patient waiting is essential for success in these more active investment strategies that seek to exploit temporary market inefficiencies.',
  '16. Convertible Issues and Warrants': '\n\nGraham emphasizes that the complexity of convertible and warrant instruments often obscures their true risk-reward characteristics, making them unsuitable for most investors. The simplicity of straight bonds or common stocks is usually preferable to the illusory benefits of hybrid securities, which tend to transfer value from investors to issuers and insiders while providing inadequate compensation for the risks assumed.',
  '17. Four Extremely Instructive Case Histories': '\n\nGraham emphasizes that these case studies demonstrate the importance of maintaining healthy skepticism and conducting thorough analysis before investing in any company, regardless of how compelling the story may appear. The patterns of fraud, leverage, and speculation that destroyed these companies are not unique to their era but continue to appear in different forms in every market environment throughout history.',
  '18. A Comparison of Eight Pairs of Companies': '\n\nGraham emphasizes that this expanded comparison reinforces the fundamental principle that valuation, not company quality alone, determines investment outcomes. The discipline to focus on price paid rather than story quality is essential for long-term investment success, as overpaying for quality is one of the most common and costly mistakes investors make in both bull and bear markets.',
  '19. Shareholders and Managements: Dividend Policy': '\n\nGraham emphasizes that shareholders must take an active role in monitoring management decisions and holding executives accountable for their stewardship of corporate resources. The passive approach favored by most institutional investors often enables poor management practices, creating opportunities for engaged individual shareholders to protect and enhance their investment returns through informed oversight and vocal dissent.',
  '20. "Margin of Safety" as the Central Concept of Investment': '\n\nGraham emphasizes that the margin of safety is not a static concept but a dynamic principle that must be applied to every investment decision, from stock selection to portfolio construction to emotional management. The intelligent investor must constantly evaluate whether adequate margins of safety exist in their portfolio and adjust their positions when these margins erode due to rising prices or deteriorating fundamentals.'
};

j.chapters.forEach(ch => {
  if (additions[ch.title]) {
    ch.summary += additions[ch.title];
  }
});

fs.writeFileSync(filePath, JSON.stringify(j, null, 2), 'utf8');

let total = 0;
let allAbove500 = true;
j.chapters.forEach(c => {
  const w = c.summary.split(/\s+/).length;
  total += w;
  if (w < 500) allAbove500 = false;
  console.log(c.title + ': ' + w + ' words');
});
console.log('\nAverage words per chapter:', Math.round(total / j.chapters.length * 10) / 10);
console.log('All chapters above 500 words:', allAbove500);
